### ISSUE TITLE
Getting a short hash is too slow

### ISSUE THREAD

**Issue by kaste** [timbrel/GitSavvy#1264]
We use `get_short_hash` which just calls into `git`. This is way too slow. E.g. the `tags` dashboard becomes almost unusable just because of that. (The defaults here are to get all tags, then we do a `rev-parse` for each tag. That doesn't scale regardless of how fast your computer is.)

**Comment by winehook** [comment]
Hello gang -- love GitSavvy, am a paying user and a big fan.  Since the latest update, the main Git Status page is much slower to update than it has been in the past.  I'll be working in my repo, make a change, and then go to Git Status main page, and there's no sign of a change to be staged.  Sometimes if I click away, then click back, it works.  Other times I have to wait maybe 5 or 10 seconds.  But this is new behavior.  Not sure if it's related to this particular issue or not, but wanted to bring it up.  Is there something i can do to adjust settings on my part to help?  I'm guessing it's just still processing the files to detect changes or something?

**Comment by kaste** [comment]
Status view has not seen any updates since last Nov.  You can enable logging via the Command Palette `GitSavvy: Enable logging`.  After that open the Sublime console.
