### ISSUE TITLE
Dangerous mistakes (drop commit instead of push) happen when pressing p 

### ISSUE THREAD

**Issue by mnieber** [timbrel/GitSavvy#1298]
It's happened a few times that I pressed `p` when I thought I was in the first gitsavvy status screen, but actually I was in the rebase screen. It's the `undo` feature that makes the rebase screen save, but in my opinion it's still not safe enough, because I almost dropped a commit without even noticing :-). Maybe this could be improved by requiring the user to also press `ctrl` in the rebase screen to do destructive actions such as `drop commit`?

**Comment by kaste** [comment]
Hm, the better shortcut would be `d` for "dropping", "discard", or "delete".  Likely "D" or any upper case letter if we want to reduce mistakes.  (Also: why "q" and not "s" for "squash"?)

Unlikely I will change this here because I never touched the rebase view, I'm neither using it or made any code changes in this area (yet?). 

You can of course do your own bindings using the Sublime Keybindings configuration. 
First make the current `p` a "noop", and define whatever key you want.

```
    {
        "keys": ["p"],
        "command": "noop",
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.rebase_view", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "meta.git-savvy.rebase-graph.entry" },
            { "key": "setting.git_savvy.in_rebase", "operator": "equal", "operand": false }
        ]
    },
    {
        "keys": ["ctrl+p"],
        "command": "gs_rebase_drop",
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.rebase_view", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "meta.git-savvy.rebase-graph.entry" },
            { "key": "setting.git_savvy.in_rebase", "operator": "equal", "operand": false }
        ]
    },

```

**Comment by mnieber** [comment]
Thanks, that should work! I will close the ticket, but if someone wants to reopen it that's fine of course.
