### ISSUE TITLE
Use tracking branch for git-rebase

### ISSUE THREAD

**Issue by uzytkownik** [timbrel/GitSavvy#1319]
Currently on large repository git rebase can take a long time as it tries to auto-detect potential rebases. To speed things up GitSavvy should us tracking branches instead of parsing git-show-branch.

**Comment by kaste** [comment]
We don't want to show just the upstream but ideally the fork point of the current branch.  Since we currently wait for the command to complete, and then process the stdout in one go, maybe it would be better to read as a stream and parse line by line.  

We use a streaming reader for the "log graph" ("Repo/File History") but here I think parsing the output is a bit more work than what we have right now.  

Would take a PR of course.

**Comment by kaste** [comment]
Or any other way to find a sane fork point.

**Comment by kaste** [comment]
Closing as I'm generally recommend rebasing from the Repo History now.  I actually deprecate the old rebase special view.
