### ISSUE TITLE
Offer autostash for rebase operations

### ISSUE THREAD

**Issue by nh2** [timbrel/GitSavvy#1337]
Currently, the rebase dialogue, and `git: quick fixup from stage` error out with

> Unable to perform rebase actions while repo is in unclean state.

when there are other unstaged changes.

Git offers the `git rebase --autostash` flag for this purpose, which atomically does `git stash` before the rebase operation, and `git stash pop` when it's done or aborted.

I propose that instead of showing the above error message, GitSavvy should ask:

> Unable to perform rebase actions while repo is in unclean state; autostash? [Yes/Now]

**Comment by kaste** [comment]
Well, yeah.  The rebase stuff herein is written in Python.  I personally have a trust problem with the code base here and actually never use it.  I found it to be okay for the happy path but usually was totally lost on any failure.  a) I don't trust the code because I saw the rest of the code,  b) it is slow.  

My hunch was to rather make a thin wrapper around the native "git rebase", basically just rewriting the TODO list and hand it over to git.  The UI for this is/or will be because it's not public yet, our normal "Repo History" view.  For example, you make a normal fixup commit, then you can select that commit in the "Repo History", open the rebase actions menu, and hit "Apply fix to 'c234de'".  Likewise you just hit `W` to reword a commit, or `E` to edit.  For these simple rewrite actions I always "autostash" btw, actually don't know why I should ask first.  

This works fast and reliable right now but you must have Sublime Text as your git editor.  Iirc I set `GIT_EDITOR` (and maybe `GIT_SEQUENCE_EDITOR`) to the current running Sublime executable + ` -w`.  It won't work or there may be some hiccup if for some systems Sublime does not work as the GIT_EDITOR.  I don't have any problems with that though on my machine.

**Comment by kaste** [comment]
Don't know if it's actually a good idea to set `GIT_EDITOR` or just to tell the user to do it.  But, hell, it's just `subl -w` anyway, no?

**Comment by kaste** [comment]
Since GitSavvy now ships new rebase commands accessible from the Repo History, a lot of them do autostash now, let me now if there is something left here.  Esp. for fixups we have different workflows now.
