### ISSUE TITLE
UnicodeDecodeError: 'charmap'

### ISSUE THREAD

**Issue by srggrs** [timbrel/GitSavvy#1371]
I encountered this error when rebasing a branch on top of master.

Here is the stacktrace (I enabled the debugging in GitSavvy before the rebase):
```bash
git rebase master (/path/to/my/repo)

Please report this error to GitSavvy:

'charmap' codec can't decode byte 0x8d in position 162: character maps to <undefined>

Traceback (most recent call last):
  File "/home/myuser/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 220, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "/home/myuser/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 299, in decode_stdout
    decoded, _ = self.try_decode(stdout, encodings)
  File "/home/myuser/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 311, in try_decode
    raise err
  File "/home/myuser/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 307, in try_decode
    return input.decode(encoding), encoding
  File "./python3.3/encodings/cp1252.py", line 15, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 162: character maps to <undefined>
```

**Comment by kaste** [comment]
Since I don't know where you're standing here I shortly explain.  We tried to decode the git stdout and/or stderr and it failed.  We try by default three encodings, first "utf-8", then the "preferred" encoding of your system (retrieved by python's `locale.getpreferredencoding()`), and then the fallback encoding from the GitSavvy settings (for whatever reason "windows-1252" by default).  

After that an error dialog should appear, telling you that "parsing" the output did fail.  Did you see it?

Unfortunately here we catch the error and present it again as "Please report this error to GitSavvy" which reads to me like "This should never happen" although it is just a normal error which can hopefully be resolved by setting a different fallback encoding.  

Now, a "git rebase" comand does not have that much output.  Maybe it had a merge conflict so it printed the commit message subjects?  Or the filenames?  Would be interesting to see what the "Repo History" prints here because it is the only special view that does not fail on encoding/utf-8 errors but just continues.

**Comment by braver** [comment]
> it is just a normal error which can hopefully be resolved by setting a different fallback encoding.

I just ran into the same, or at least a similar, issue. Indeed I got a popup telling me maybe I need a different fallback_encoding. 

I don't know what to set it to though. It seems to bork on the initial commit of the git repo, which has some time ago been converted from an SVN repository. There is about 15 years of legacy in that initial commit and I really don't know what encoding setting will prevent GitSavvy from continually running into this error. 

The output it tries to parse seems to be from this command:
```
git show --no-color --format=fuller --stat --patch c587957cc
```
... which on the command line outputs the list of a couple thousand files (loads of libraries and dependencies that where checked in ages ago are in there as well) added in that initial commit in the repo. It's just a list of file paths... is it a weird character in there somewhere that causes the problem? What should I be looking for?

**Comment by braver** [comment]
Oh, looking at the output in more detail it's not just a list of files, it's the content of that entire first commit. All 700k lines of it 😲 . I do spot some BOM's in there, that usually spells trouble. Is that the culprit (I'd think what would be covered by cp1252).

<img width="358" alt="Screenshot 2020-11-04 at 12 27 01" src="https://user-images.githubusercontent.com/2543659/98106025-13720080-1e99-11eb-9f9b-f86d5f0705e0.png">

**Comment by kaste** [comment]
Hi @braver!

To resolve this issue, don't try to show this commit. :grin:

I think the general implementation in GitSavvy is a bit naive here.  How I understand it, showing a commit with a patch can show multiple files, each could use a different encoding.  In GitSavvy, for this code path here at least, we decode the *complete* stdout in one go.  So you basically need a super-encoding for the whole output.  

For the Repo History, I switched to line by line decoding plus a fallback, streaming the stdout in.  Since "show-commit" is also a read-only view it would make sense to do the same here.

**Comment by braver** [comment]
> don't try to show this commit.

Yeah, it's in a private repo and apparently the commit has the entire codebase of the primary repository we work on here... so it would be kinda bad form to share the commit here 😁 

It's not uncommon for large repositories to regularly "trim" the history down. Especially if the repo also contains libraries or binaries like images etc. the repo might get unwieldy and you basically squash everything up to a certain point into one commit. We did that here because the SVN to Git conversion would otherwise take over 24hrs to complete and the resulting git repo would be so massive you couldn't clone it quickly either. I've seen other clients die trying to grok this huge "initial" commit though.

**Comment by kaste** [comment]
I meant don't try to show this commit in GitSavvy.   I thought this just shows up because you might have the bottom panel open in the Repo History.  Do you want to read that commit actually in Sublime?  700k lines?  Just stream it into `subl` from the Terminal for now.

**Comment by braver** [comment]
Oh right. I just hit some keyboard combination or whatever and the panel opened. I think I was looking at a file history with just a few commits and browsed to the first one by accident or whatever. I'll try not to look at the commit in the future 😉

**Comment by kaste** [comment]
That's a huge trade-off here with that initial commit.  Every file log, Line History, grepping "-S" or "-G", blaming.  Probably all this points to the initial commit in the end.

**Comment by braver** [comment]
Jup.

What would help is if I could put this in my project settings:
```json
"GitSavvy": {
    "log_show_more_commit_info": false
}
```

(I can put it there, but I don't think GitSavvy reads project settings?)

**Comment by kaste** [comment]
Well, it goes into `settings: GitSavvy: graph_show_more_commit_info` for project files.  Might be buggy as I don't know which concrete setting is actually an app wide (global) setting.  But `graph_show_more_commit_info` does not forbid the shortcut `m` to toggle the panel. It just sets the initial state.

Honestly, you don't trim the history regularly, but instead do sparse clones and checkouts.

**Comment by braver** [comment]
> Honestly, you don't trim the history regularly, but instead do sparse clones and checkouts.

I've seen it done before, it's not uncommon practice and shallow clones come with their own issues. Shallow clones work for the CI environment, but to save time and space on development you really don't want to deal with shallow clones. Anyway, sometimes there is no good solution and you pick one 🤷.

> Well, it goes into settings: GitSavvy: graph_show_more_commit_info for project files.

Thanks, that works. Guess I was looking at the wrong setting. It's been a while since I used GitSavvy. It's like an old pair of jeans though, good stuff.

**Comment by kaste** [comment]
FWIW, new GitSavvy version will not give up and show modal dialogs when decoding a patch or diff fails.  So it will probably just hang Sublime if you throw your 700k lines patch now.  That's a win. 😏

**Comment by braver** [comment]
Progress! 🏎

**Comment by kaste** [comment]
Closing as all encoding stuff has already been rewritten
