### ISSUE TITLE
"github: create pull request" should use the "default" branch as target, not the literal "master" branch

### ISSUE THREAD

**Issue by rwols** [timbrel/GitSavvy#1384]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/2431823/95627092-deca7f00-0a7b-11eb-92cb-92663306cc60.png">

When I run "github: create pull request" from the command palette, a pull request is created from my topic branch. This is a great feature. However, it targets the "master" branch as base, but the default branch is not a branch called "master".

**Comment by kaste** [comment]
This can be configured manually with the `github: set remote for integration` command.  (A misnomer?)  Maybe there is an API call for this as well but asking the Internet is usually slow(er).

**Comment by rwols** [comment]
This works. But where is this setting stored? It feels somewhat magical now :)

**Comment by kaste** [comment]
That goes into the .git/config file.  The fallback/default is "origin/master" which is iirc not always the recommended approach.  For example, if I fork a repo I think a lot of tools make the fork "origin" and the original repo "upstream".  (I think the GitHub cli does that.)

**Comment by kaste** [comment]
Yes, looks like it does. From https://cli.github.com/manual/gh_repo_fork

```
# Create a fork for the current repository.
~/Projects/cli$ gh repo fork
- Forking cli/cli...
✓ Created fork user/cli
? Would you like to add a remote for the fork? Yes
✓ Renamed origin remote to upstream
✓ Added remote origin
~/Projects/cli$
```

**Comment by rwols** [comment]
Interesting approach to put it in .git/config, I indeed see it set there

```
[GitSavvy]
	ghRemote = origin
	ghBranch = st4000-exploration
```

Anyway, thanks for a solution.

**Comment by kaste** [comment]
The original authors didn't want to rely on the Sublime projects.  Basically they want to use `subl .` in a Terminal and moan about Sublime not "attaching" the project file to the Window even when there is a project file in that folder to use.  IMO a long standing annoyance I often hear in SublimeLinter issues/comments.  People don't use projects just because of that.

Anyhow, I think this should just work.  Let's see if there is an easy solution to this.

**Comment by randy3k** [comment]
What annoys is that the target branch for github integration is stored in `.git/config` but the target branch for the rebase dashboard is stored as project/view settings `git_savvy.rebase.base_ref`. I guess we should have a consistent way to store these kinds of information.

**Comment by kaste** [comment]
Hm, the issue here is introduced by a 1% feature.  Naturally, GitHub opens pull request against the *original* repo.  It then uses the default branch by default.  Note that of course everything is flippable via their UI.  

Within GitSavvy, a feature has been implemented so that you can "easily", via the said configuration here in this thread, open pull requests against a *fork*.  (Basically, you make the configuration here, and then don't have to flip the dropdown on GitHub's page.)  I say this is a 1% feature because it is not within the notion of a "fork".  A fork is made to make code changes with the intent to push them upstream.  Usually, if you don't want that, you could make an independent clone.  Anyhow, if you use this feature, our "Show Issues", "Review PR", or here the "Create PR" commands actually target the *fork*.  (So you see and close the issues on your fork not on the original repo.)

If you don't explicitly "set remote integration" (aka the automatic/default behavior) you can have inconsistencies.  For example, GitSavvy could show the issues of your fork but open pull requests against the original repo.  Or, it shows correctly the issues of the original repo but does not use the correct default branch on the origin for the pull requests.  (Maybe the original repo doesn't even use "master" but switched to "main".)

1. We can solve this by asking GitHub for the default branch.  This slows down (for example ~250ms) the "Create PR" command on every invocation.  On the other hand, it solves the problem for all cases, usually without any configuration, and makes the behavior consistent.[*]  

2. We can open PRs always against the original repo *except* if the user configured manually using "set remote integration".  Then we never ask GitHub, we either set the configured branch or not, relying on the default behavior of GitHub.  With that we can have some inconsistency, namely showing issues (etc) of a fork while creating PRs against the original. 

[*] Although (1) seems preferable, it does not have to be the better user-experience.  A user might decide up-front to make an upstream change.  The user *forks*, and uses just that fork locally.  T.i. the local repo has only *one* remote set, whereby the *full* integration in GitSavvy requires *two* remotes, one where you can push code to (the "origin" or *fork*) and one where the issues and pull requests reside (the "upstream"). In that case (2) will do the right thing, and open the PR against the original repo, whereby (1) will require flipping the dropdowns in GitHub's UI. 

From the code, I've implemented both versions, first (1) then I thought ... ah well a bit slow, then (2).  Both are 10 liners.

**Comment by rwols** [comment]
The default branch of the repo I push to has changed names from `st4000-exploration` to `main`, but the package creates a Pull Request proposal for the `st4000-exploration` branch still. Is there perhaps any cache file I should delete to make this work again?

**Comment by randy3k** [comment]
IIRC, the only related file is `.git/config`. Perhaps you need to run again the command `github: set remote for integration`?

**Comment by rwols** [comment]
ah yes, there's a `[GitSavvy]` section in `.git/config`. Thanks!

**Comment by kaste** [comment]
You should maybe not run `set remote for integration` but remove the configuration manually from the `config`.  The defaults should just work now.

**Comment by rwols** [comment]
> You should maybe not run set remote for integration but remove the configuration manually from the config. The defaults should just work now.

I did this, and it results in the same: a GitSavvy section in .git/config:

```
[GitSavvy]
	ghRemote = origin
	ghBranch = main
```

thanks for the pointers

**Comment by kaste** [comment]
🤞 Iirc you have set `origin` or `upstream` as the remote name. Then `git remote show origin` should show you `HEAD branch: XXX`, and that's the default branch.  So there should be no need to setup anything.

**Comment by rwols** [comment]
Alright, trying to get this to zero-conf this thing.

>  Iirc you have set origin or upstream as the remote name.

Yes.

Also I removed the [GitSavvy] section in .git/config and restarted ST.

> Then git remote show origin should show you HEAD branch: XXX, and that's the default branch.

Yes, if ran from my terminal.

> So there should be no need to setup anything.

Next time I make a pull request I'll find out :)

**Comment by randy3k** [comment]
AFAIK, you only need to use `set remote for integration` if you have forked a repo and create a pull request to upstream for your fork.
