### ISSUE TITLE
GitSavvy doesn't open status page

### ISSUE THREAD

**Issue by IPWright83** [timbrel/GitSavvy#1410]
I'm finding fairly frequently that GitSavvy isn't opening properly for me. I'm super disappointed as GitSavvy is by far my favourite package, as is the sole reason I've not switched to another IDE like VSCode (kudos to the author!).

However I'm finding that when I press the key combination sometimes GitSavvy's not doing anything. I've run the steps to create a debug log and it's completely empty. With the console view visible I can see this output when I hit my shortcut keys `ctrl+alt+s`:

```
 (D) [  8ms] $ git status --porcelain -z -b
 (D) [  6ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 (D) [ 23ms] $ git stash list
```

The usual way to resolve this problem is to disable and then re-enable the plugin, which often causes it to fix itself (though not 100% guaranteed). I'd note that this is on a small repository where git actions are pretty quick, and typically commands like `git status` via a terminal respond promptly at the same point that GitSavvy is stuck.

I'm on Sublime Text 3 Build 3210. I'm using build v2.27.3 of GitSavvy.

**Comment by kaste** [comment]
Hm.  Very strange.  Now, the three git commands you see in the console are actually coming from the status page.  Are you sure there is no status view open at that time?  Maybe it just doesn't get the focus?

Since we push updates rather often, maybe downloading and hot reloading fails, or is too slow.  Maybe immediately open the console the next time you'll have this.  Package control should print any updates.  (You could for example subscribe to the releases here, then you know when to expect a new version.).

**Comment by IPWright83** [comment]
Happy to subscribe to releases to check. 

Sorry, I should be slightly clearer. The status page tab opens in Sublime, but remains blank, so it's almost as though it's started everything off, but something's interrupted it to stop it from finishing.

**Comment by IPWright83** [comment]
Just to note, last time it happened was when I logged this issue. It looks like the last release was 21 hours ago - I don't know if that's the typical lag you'd expect for it to hit the Sublime Package repository? It feels a little long from my experience with other packages.

**Comment by kaste** [comment]
Blank view as in completely nada, or just the template with holes in it or stale data.  (Then how could you tell it's the status page?)

From hitting release here and seeing it in Package Control might take an hour.  But you only get updates on a Sublime restart.

**Comment by IPWright83** [comment]
It's opens/sets focus to a completely blank page (though I have a feeling the tab name is correct e.g. `STATUS: repName` though I'll have to verify that next time it happens.)

**Comment by kaste** [comment]
The title or name of the tab is set directly when creating the blank view.  There is really nothing that can go wrong here. 

There are a few things that can go wrong later.  Not that I see it, but the code is also not that easy you could *just* see it.  After each of the 3 git calls, we actually call for a render.  (The git calls succeed and finish otherwise we would throw here.)  

We then have 1) a lock because we can't render in parallel.  I don't see how we could deadlock here.  If so, not only this view should not render but Sublime should lock as well.  (The mostly empty template renders on the main thread.  If we lock here Sublime freezes.  The other render on the `(D)` thread as per console log.  If we lock this thread most Sublime plugins will not work anymore.)  This is all easy to test on your side.  2) We skip render because the actual "state" (the "what we should render") did not change.  That's from a logical standpoint not possible on a fresh start because on start we start with the empty state.  There could be some inference if there are multiple status views open.  3) The view we act upon in the code got invalid.  So we actually render to nothing.  This would mean we had for a short period two views and a race between them.  But you should notice two such views.  

For the next time it happens, a) look at the console if Sublime itself puts something here.  b)  look if you have other gitsavvy views open  c) can you just by closing the blank view and retrying, or by switching back from the Sublime app and bringing the focus back in resolve it.  

Still my hunch is, that the actual commands, for example the actual "render-this" command is not registered.  (Sublime will not throw if we either render to nothing or call a command which is at that moment not registered.)

**Comment by IPWright83** [comment]
Unfortunately I've been doing lots of admin recently, but I've just encountered the issue again today. I notice there was a release early yesterday and I've had my machine shutdown since - so I think that potentially rules out the in-place upgrade of the package.

Interestingly today the first thing I encountered was that I previously had the Status Page open in my workspace/project. I'd made a change and it wasn't updating (even pressing the refresh hotkey). So I closed the status page and tried to re-open it.

A) I've enabled the GitSavvy debug log and sublime logging commands, and this is the console output. I've got a bunch of other garbage in the console (logged a bug with that package for being so noisy).

```
XoFixCommand -> project_root -> /home/iw651/src/team4-aws-template
XoFixCommand -> return -> True
command: gs_show_status
 (M) [ 11ms] $ git rev-parse --show-toplevel
 (D) [  6ms] $ git status --porcelain -z -b
 (D) [  6ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 (D) [ 27ms] $ git stash list
XoFixCommand -> is_enabled?
XoFixCommand -> project_root -> None
XoFixCommand -> xo_start_dir /home/iw651/src/team4-aws-template
XoFixCommand -> xo_path /home/iw651/src/team4-aws-template/node_modules/.bin/xo
XoFixCommand -> environ.path -> /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/iw651/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/bin
```

B) I've included a GIF just so you can see what's going on. Picture tells 1000 words n' all that.

![gitsavvy](https://user-images.githubusercontent.com/1374775/98795084-b975bb80-2401-11eb-9f39-ef2bb77087b1.gif)


C) Switching focus doesn't do anything - if there's anything else you'd like me to try I'll do my best to keep it in this state for a little while. I'm planning on running some more tests (e.g. close sublime and try again with the status already open, repeat with the status page closed etc) to see if I can identify a trigger.

**Comment by kaste** [comment]
> so I think that potentially rules out the in-place upgrade of the package

The upgrades are always in-place.  You start Sublime, it loads the installed packages as usual, *then* Package Control will look for updates, and so on.  (Package Control will only look for updates at/after start up.)

Right now, I have no idea what is going on here.  I would have liked the console output from the start up though.  Esp. if Package Control says "No updates", or "Updating X failed...".

**Comment by IPWright83** [comment]
@kaste I'll try to remember to open the console each time I load up just in case and record the output in here again next time it happens.

**Comment by kaste** [comment]
Closing as stale
