### ISSUE TITLE
could not parse Packages/Julia/Julia.tmLanguage

### ISSUE THREAD

**Issue by rwols** [timbrel/GitSavvy#1454]
I'm seeing this presumably benign error message in the console:

```
GitSavvy: could not parse Packages/Julia/Julia.tmLanguage
```

**Comment by kaste** [comment]
Yeah, we lookup each syntax file at startup to populate a *file extension* to *syntax* map.  (which we then only use as a fallback because most of the time the user has some file open so we really read the `syntax` key from the settings.)  

That being said, `tmLanguage` files are of course rare these days, don't know for how long we still read them in, and the (latest) Julia package doesn't ship any.  Maybe you used a pinned version?

https://github.com/JuliaEditorSupport/Julia-sublime

**Comment by kaste** [comment]
Closing as the upstream issue has been resolved.  At some point we drop reading `tmLanguage` files.  For now it is probably okay to log here as GitSavvy has no debug setting which you could enable to get the information at Sublime startup.
