### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by Jorman** [timbrel/GitSavvy#1524]
Hi,
I'm not sure if that is a GitSavvy issue, in case it wasn't I apologize, but from console ssh works but through GitSavvy doesn't, and I can't understand where I'm wrong.

In ST3 I installed GitSavvy, and then I set up the api_tokens from GitHub, I tried to give all permission, not only the two recommended, but every time I try to push one commit to my repo I get this error
```
$ git push origin master:master

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
So, I log to my server via ssh and I generated ssh key pairing then under GitHub I created one `SSH keys`, and I pasted the public key inside it.
Now if I push from my ssh console, all is working, but if I push via ST3 I always get the error. I tried to find the place where I've to set up the ssh public key but I can't find it

Anyone has some idea about this?

J

**Comment by kaste** [comment]
So it's now working on the Terminal but not in Sublime Text?

We're basically doing the same as on the command line *but* as a child of Sublime Text; t.i. we're in the environment ST sees and maybe you load different things during the shell startup.  

You usually can try to close all ST, and then start it from the command line using *subl .* so that it inherits the environment of the shell.

**Comment by Jorman** [comment]
Yes.
I think I "found" the problem, but I don't know, not yet, how to fix it.
I think, let me know if I'm wrong that is a "user" issue, I try to be more precise to better understand the actual situation:
Local pc over Windows
Remote server over Debian
Terminal session with root user
Shared folders with nobody:nogroups defaults, so over local anyone (it's only me) can share, delete and so on, are public folders.

Now, if my thought are right, I created an ssh key pair with root, but Sublime Text is run from my local pc and all the files are nobody:nogroups, so Sublime Text, during the git push can't access to /root/.shh folder and files.
Make sense this?

If yes, nodoby has no home folder and is not available, so how can I set up one ssh key pair? There's a possibility to configure Sublime Text or GitSavvy to handle ssh keys?

J

**Comment by kaste** [comment]
I don't think I can help here as this is a rather complicated setup; too many things can actually go wrong in such a setup.  But is `Host key verification failed.` still the error message? Reading the original post I thought this was only the *initial* error message before you re-did the ssh key registration.  

You can google the exact error message, but -- **spoiler** -- "key *verification* failed" indicates it can read the key but its verification fails.  (So you would need to anew the key.) 

You may want to try the "https" protocol for GitHub, it is recommended anyway, and easier or more natural on Windows for sure.

**Comment by kaste** [comment]
If you need to, you can modify the `env` (https://github.com/timbrel/GitSavvy/blob/63d8503e6e970db0e7e72cfbf8a36dbe8656ff11/GitSavvy.sublime-settings#L28) and set git "pre-flags", e.g. `-c <name>=<value>` settings, using `global_pre_flags` (https://github.com/timbrel/GitSavvy/blob/63d8503e6e970db0e7e72cfbf8a36dbe8656ff11/GitSavvy.sublime-settings#L165) via the GitSavvy settings.

**Comment by Jorman** [comment]
Thank you, @kaste, for your time.
Yes, the error is always the same, and via Terminal, I can push the commit, for that reason I'm searching a way to edit the git config file and set a new path for private key.
Like I said, I'm not sure is a GitSavvy issue because the setup is "strange"
I also know that Sublime Merge came in play at certain point, so I'm pretty unsure where I've to solve this.
Are you suggesting to set a custom env to specify the private key? Or do you point out the way to use https?

**Comment by kaste** [comment]
Is this also a language thing? Sprichst Du auch deutsch?

It is confusing me because you have a remote server you control but then also want to push to GitHub for which using "https" is for sure the easiest way forward.  And it looks strange because you're actually *on* (not *over*?) Windows for which you don't manually configure ssh. On Windows you just use the credentials manager unless you use an ancient git version.  

> Yes, the error is always the same, and via Terminal, I can push the commit, for that reason I'm searching a way to edit the git config file and set a new path for private key.

What do you want to put in the git config file? Especially the git config would be used on the Terminal as well but the Terminal already works.  Whatever you put in the config file could be set in `global_pre_flags` as a `-c ...` key-value-pair.  So that's where this flag comes into play. 

The ssh-agent usually is controlled by and controls ENV key value pairs if I'm not confused right now. Such env keys could be set manually using the `env` setting.  (Although an easier setup that works automatically is preferred because usually we forget how such things work in the long run so they break often the next time we change our system.)  

What's up with Sublime Merge? SM is a completely different (stand-alone) app.  GitSavvy runs "hosted" within Sublime Text.

**Comment by Jorman** [comment]
Ok, no, I don't speak German.
You're right, I think I've some "bad" ideas, I thought (actually I was convinced, and I don't know why), that if I've to edit and work on server side I need the key pair from server side, but actually I'm working with ST over windows and the project is only saved in a shared directory, can be a local one too, it would make no difference.

So I've to set up all like if I work from windows. Am I right?
So now the question, why if I configured the token I get this error message?
![image](https://user-images.githubusercontent.com/5203988/147416825-b686781f-db73-4176-9d71-8ba489f572ec.png)

**Comment by kaste** [comment]
Forget the API tokens, `git push` doesn't need any.   We need these tokens to read PR's and issues and maybe fork a repo.  For the basic functionality t.i. `pull/push` git is used *just like* on the command line.  Really we just call `git push` and other commands and have a nice UI around it.  *But* we don't run these commands on the *typical* shell, which are interactive, login shells, (basically you run some bashrc or whatever scripts to setup your shell), we run the commands as subprocess of Sublime Text.  ST is our host.  *We inherit the environment Sublime Text has.*  

So that's how it works. Typically you want to start ST in a way that it has all environment variables set so you don't need to do anything for GitSavvy and all other possible plugins (SublimeLinter, LSP) you might want to use.  You can also manually change the environment using GitSavvy settings.

If you're on Windows it is very likely you actually run and have to configure everything on the Windows side.  There are always some advanced virtualization techniques but I read it that you only have a network drive or something like that.

**Comment by Jorman** [comment]
Ok, right, I set up the ssh connection.
I configured from scratch the ssh with GitHub, and you're right, maybe some missing key...

Thanks for your help

**Comment by kaste** [comment]
Closing, looks like solved.
