### ISSUE TITLE
Filter pull requests by those requiring review

### ISSUE THREAD

**Issue by nikhil-marathe-skydio** [timbrel/GitSavvy#1937]
It would be nice if the "github: review pull request" action could narrow down the PRs to only those awaiting review from me (perhaps just accept github filter syntax?). Right now, on large projects, GitSavvy fetches the first N PRs, by sequence number. If none of these are the ones i want, I have to go hitting next page, and mentally keep track of whether the current list will have the PR I want.

I understand this is a request with multiple different solution spaces:
- always filtering by "review requested", but then various organizations use the Assignee instead.
- allowing a project specific setting
- making the "review pull request" pop up a filter query or something
- needing to support some syntax that works across the various provides (GitHub/GitLab)

So no pressure, I just wanted to kick off the conversation.

**Comment by kaste** [comment]
We fetch 100 PR's at once and you still have to hit next.  😱

* Actually, every (almost) setting is also a project setting, so that would be okay.  Still the command itself should take a parameter so that one can easily register different variants of the command in the Command Palette.  
* We use https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests this API and there is no query parameter if I glimpsed correctly.  (That would have been the easiest solution to let the user just provide a query.)  Maybe you could research the API of how to do that actually.

In the long run, I would like to have a special view just for pull requests.  This would be just more convenient.  - We could filter on the fly. - We could show the status checks. Etc.

**Comment by kaste** [comment]
I actually also have code against `"https://api.github.com/graphql"` but we don't use it here right now.  I don't know if that endpoint is also valid for organization and on-premise versions of GitHub.  

It is likely that graphql supports fine-grained querying but writing the query is error-prone and complex so that we can't put it in user's land.

**Comment by nikhil-marathe-skydio** [comment]
Yea, I think the graphql endpoint would be required. I expect it is valid for organizations as well, since IDEs like Jetbrains are able to show that.
I like the idea for a special view for pull requests. That seems much nicer than the list.

Another option (this is unrelated to this bug report), would be to, in the list of pull requests, allow the user to type `#<pr number>`, and in that case, always retrieve that PR, instead of using the filtered list.

**Comment by kaste** [comment]
Either graphql or REST, for most use-cases we would still fetch all open pull requests to do the filter "offline", locally, and very often then as-you-type.  How many open PRs you're dealing with?  You would still need to dig into this to see which properties are actually relevant here. I see `"assignee":`, `"assignees":` (huh?), `"requested_reviewers":`, `"requested_teams":` in the pr responses.

**Comment by kaste** [comment]
I have been told that there is actually a search API, https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests, which we can use as a drop-in replacement afaik.  The search endpoint supports the query format  and feature we all know from the website.   So the minimal viable solution would be to parameterize the GitSavvy command so that users can add new variants to the Command Palette, e.g.:

```
    {
        "caption": "github: review pull request",
        "command": "gs_github_pull_request",
		"args": {"query": "assignee:your_name state:open"},
    },
```
