### ISSUE TITLE
Ignore EOL-whitespace in Inline Diff view

### ISSUE THREAD

**Issue by hanoii** [timbrel/GitSavvy#291]
I can't figure out if this is something I am understanding wrong, but how does whitespace toggling in diff works?

I set the setting

```
{
        "inline_diff_ignore_eol_whitespaces": true
}
```

But I am also looking for a way to manually toggle this on diff views. Do I need the setting if I want to toggle it?

Also, is it safe to stage/unstage a hunk or linke while using htis?

Thanks,
Ariel.=

**Comment by stoivo** [comment]
what it does in inline diff is to append  `--ignore-space-at-eol` to the command  and if you look in the git docs you will find   
```
--ignore-space-at-eol
   Ignore changes in whitespace at EOL.
```
I don't use this setting in my use of GitSavvy.  But there you have what is does in the background. 

Do you think it would be good to have the toggle option in inline diff the same way we have it in diff view?

**Comment by hanoii** [comment]
I think so. I use the inline diff almost exclusively, I am unsure if having that will prevent the line/hung staging/unstaging to work. But definitely a good thing to have on inline diff as well.

I have to say it's amazing how gitsavvy has matured since the first versions.

**Comment by divmain** [comment]
The `inline_diff_ignore_eol_whitespaces` is intended really only for the situation described in #177.  There is no way to toggle the behavior in the actual diff view without changing the setting.

In the inline-diff view, there is new functionality that might look similar (press `s` to toggle ignoring of whitespace).  However, (un)staging of lines and hunks will not work in this mode, because the correctness of the generated diffs cannot be guaranteed.

If `inline_diff_ignore_eol_whitespaces` is what you're really looking for in the inline-diff view, I'm definitely open to adding the functionality.  I don't have a repo at-hand to quickly reproduce the issue that the option alleviates, and it is not something that I've run into on any of my projects, so it will probably take a lower priority to some of the other issues in my queue.

However, if it is something that is bugging you, I'd be happy to give any guidance that would help you make the attempt yourself.

**Comment by kaste** [comment]
Closing as stale
