### ISSUE TITLE
Better branch deletion workflow

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#312]
Currently the options on the branch dashboard are:

`[d] delete                                    [D] delete (force)`

They both give the same warning that you're about to do something destructive.

The user probably doesn't know the distinction between the two, which is that the first one refuses to operate if the branch hasn't been merged into something else yet.

I'd suggest this workflow:
1. There is only [d] delete. (Probably without the warning - deleting a merged branch is not very destructive.)
2. If the delete fails, then display the message from Git, with a question: "Do you wish to force this deletion? You will have unreachable commits that will eventually get deleted."
3. If user answers yes to that question, then run `git branch -D ...`

**Comment by ramiel** [comment]
Probably showing that a branch is merged in the interface would help too. I cannot understand if is already shown or not.

**Comment by divmain** [comment]
Hey @ramiel.  That's an interesting thought, but somewhat problematic, I think.

Just showing whether a branch is merged or not is probably not as useful as showing whether is is merged with the primary development branch.  If we stuck with the underlying Git semantics, it could easily suggest something to a user that is not actually true ("my branch has been merged into master").

But, since not everyone uses `master` as their primary development branch, there'd be no consistent way to determine whether a branch or commit or ref was merged.  At first look, this would cause a significant performance hit, as well.

I'll keep this in mind though - there may be a way to incorporate it.

**Comment by ramiel** [comment]
The information should always be `this branch is merged with the current branch` which is also the information you get with `git branch --merged`.
Btw probably you're right. I use this information to know if is safe to delete a branch and to have an hint on which branch has been merged after a pull. In any case it can be useful but is not vital of course.

**Comment by kaste** [comment]
This has been implemented in #1280 released with v2.22.0 (March 2020) actually.
