### ISSUE TITLE
Enhance commit view interactivity

### ISSUE THREAD

**Issue by divmain** [timbrel/GitSavvy#50]
Follow-up for changes seen in #45.
- [ ] convert commit view to `ui.Interface`
- [ ] enable region-based retrieval of commit message
- [ ] toggle-able display of relevant diff
- [ ] toggle-able display of commit summary (ala `git commit --dry-run`, see #107)
- [ ] add embedded syntax-highlighting for diff (defining scope for region)
- [ ] **investigate:** stage files from commit view

**Comment by divmain** [comment]
- [ ] convert commit view to `ui.Interface`
- [ ] enable region-based retrieval of commit message
- [ ] in-view toggle-able display of relevant diff
- [ ] add embedded syntax-highlighting for diff (defining scope for region)

**Comment by yyyc514** [comment]
Why we're at it any objection to staging files from the git commit when users have turned on viewing commit summaries?

**Comment by alextegelid** [comment]
I often forget to stage some file and I don't think it's a big deal closing the commit message, returning to the status view and stage the remaining file/files from there

**Comment by yyyc514** [comment]
Yeah, I've kept doing the same thing and if I'm seeing the problem on the commit view I'm not sure why I shouldn't able to just solve it right there.

**Comment by divmain** [comment]
Hmm, I'll think on that...  Updating description to reflect possible enhancement.

**Comment by divmain** [comment]
Related to #89.

**Comment by kaste** [comment]
Relevant parts have been implemented here.  You can unstage and discard right in the diff.  You cannot *stage* as we're only showing what gets committed.  T.i. it is either staged or we're in `--all` mode.  

Unstaging in `--all` mode is not implemented and would be interesting, maybe.  Since technically nothing is staged in that mode, we would stage everything but the hunk/line the user wanted to unstage.  And the of course switch away from `--all` mode to the normal commit-whats-staged mode.  🤔
