### ISSUE TITLE
Feature request: add diff highlight to all diff views

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#527]
Currently it's only used in inline diff, and I would personally benefit having it in diff / diff cached views.

Current implementation discussed in  #141

**Comment by stoivo** [comment]
I think we have what you want, look here http://recordit.co/bz3BUJPjAD

https://github.com/stoivo/GitSavvy/blob/7bd7aea27b490399820c433c47f7536d58905835/Default.sublime-keymap#L537-L545

https://github.com/stoivo/GitSavvy/blob/7bd7aea27b490399820c433c47f7536d58905835/core/commands/diff.py#L118-L130

**Comment by asfaltboy** [comment]
Yep I want word diff, but I want it by way of color highlight instead of side-by-side words, such as implemented in inline diff (#141):

<img width="355" alt="687474703a2f2f636c2e6c792f696d6167652f3164305834333234314932712f496d616765253230323031352d30342d3133253230617425323031312e34392e3234253230414d2e706e67" src="https://cloud.githubusercontent.com/assets/321520/21778455/bf4b3594-d6a3-11e6-8e64-0ea38882c550.png">

**Comment by stoivo** [comment]
so inline diff all diffs?

**Comment by asfaltboy** [comment]
Yep, inline diff should only differ in that it allows shortcuts to staging/unstaging. Other than that it should "look" identical to the other diff commands we have; but it currently isn't.

**Comment by divmain** [comment]
I'm hesitant to move forward with this.  I use the diff view to copy patch files.  Sometimes I end up editing them, sometimes I use it for review, sometimes I paste it into Slack.  I like the idea of a view that is _like_ the inline-diff view, but shows info for all files in working/staging.  But I do not believe it should replace the existing diff view.

**Comment by stoivo** [comment]
I agree that is should not replace the existing one. Maybe we can start with allowing toggeling option "--word-diff" like do for diff.  https://github.com/stoivo/GitSavvy/blob/7bd7aea27b490399820c433c47f7536d58905835/core/commands/diff.py#L118-L130

**Comment by kaste** [comment]
I'll think I try an implementation here.  I just improved the word-diff feature but what git gives us in that mode is very often not helpful and more readable.  On the other hand, the typical intra-line highlighting, e.g. like on GitHub, is usually very helpful. 

Don't confuse *our* inline-diff with this intra-line highlighting.  Our inline diff essentially shows the complete file with some extra lines (the deleted ones) and added, colored regions.  The diff views shows normal patches, we can modify and copy-paste around.  We would just add some colored regions which highlight simple modifications between a and b. 

Given a GitHub diff view:

![image](https://user-images.githubusercontent.com/8558/69478858-63c29080-0df7-11ea-8f3a-8677a6b1a5f7.png)

In this case we would highlight the added `, ''` in the b part. In a we wouldn't highlight anything.  (GitHub does syntax highlighting here which we don't have.  In our diff views a is just red, b is green, and everything else is white plain text.  And we have a `+- ` markers as the first char because we're showing normal patches.)

At the moment I don't see the need for removing the `+- ` markers. (It would make the highlighting easier though.) 

WDYT?

**Comment by kaste** [comment]
Current state:

![image](https://user-images.githubusercontent.com/8558/71033640-04b31b80-2118-11ea-99f2-f47bb8e140e3.png)

![image](https://user-images.githubusercontent.com/8558/71033844-6c696680-2118-11ea-882f-a7954fe6f2f9.png)

I probably could do syntax highlighting as well, but now most lines are just red and green.  Syntax highlighting only for the context lines? Is it possible to have a say background red/green and on top of that highlighting regions.  So basically, I don't think the syntax highlighting would be the problem, but we sure want these red/green lines as well. And even if we have a red background for a deleted line, what if a syntax colored word doesn't have enough contrast to be easily readable.  How the hell make this beautiful because e.g. on GitHub they control the color scheme, but in Sublime we generally don't, and if a user has his numbers or equal punctuations red, we might end up with red on red text.

If I do this only for the context lines on the other hand it could look like Kindergarten because as I said we don't control the color scheme.
