### ISSUE TITLE
Signing fails via GPG 

### ISSUE THREAD

**Issue by franciscolourenco** [timbrel/GitSavvy#596]
Related to #581 but not on windows.

```
`/usr/bin/git commit -q -F -` failed with following output:

gpg: cannot open `/dev/tty': Device not configured
error: gpg failed to sign the data
fatal: failed to write commit object
```

On the terminal it works, and no password is asked. I guess it is cached or handled automatically with 
```
[credential]
	helper = osxkeychain
```

Since no interactin is actually required, is there any configuration possible which allows this to work?

**Comment by aristidesfl** [comment]
Any solutions for this? Right now is not possible to use Gitsavvy with signed commits at all.

**Comment by stoivo** [comment]
@aristidesfl, sorry for not commenting anything. 
@asfaltboy @randy3k any experience here? I dont.

**Comment by divmain** [comment]
@aristidesfl have you seen the docs for [signing commits with GPG](https://github.com/divmain/GitSavvy/blob/master/docs/commit.md#signing-your-commits-with-gpg)?  This method should work on Windows.

**Comment by aristidesfl** [comment]
@divmain Hadn't seen them and I was missing 
 ```
[core]
   askpass = git-gui--askpass
```

but the error persists, and in the command line it still works like usually.

**Comment by divmain** [comment]
Are you prompted for the password via `gitgui` when committing at the terminal?  Or are you prompted for password in the terminal?

**Comment by aristidesfl** [comment]
@divmain at the moment I'm not prompted at all, I believe because of `gpg-agent`.

**Comment by aristidesfl** [comment]
Isn't gpg is responsible for asking for the private key password? are you sure that `git-gui--askpass` is involved in asking in commit signing? - as opposed to ssh key and http auth passwords

**Comment by divmain** [comment]
Can you check to see if [setting `no-tty` in `~/.gnupg/gpg-agent.conf`](https://github.com/kemayo/sublime-text-git/issues/475) helps?  If it does, we should be able to set the appropriate environment config from Sublime so that you don't have to set this globally.

**Comment by aristidesfl** [comment]
@divmain that solves the issue. that last comment makes a lot of sense. Possible to streamline with Gitsavvy?

**Comment by divmain** [comment]
Sweet!  I'll leave this open until we push a fix into master.  Thanks for confirming!

**Comment by stoivo** [comment]
@divmain, did you see anywhere if it is possible to override that with a environment variable?

**Comment by aristidesfl** [comment]
@divmain did you edit your comment? setting `no-tty` in `~/.gnupg/gpg-agent.conf` doesn't do anything, but in `~/.gnupg/gpg.conf` is does.

**Comment by isnifer** [comment]
@aristidesfl I think I had a similar problem. And I've solved it like this:
```
git config --global gpg.program $(which gpg)
```

**Comment by aristidesfl** [comment]
@isnifer thanks, unfortunately it doesn't change anything in this case. I think @divmain might have a plan already?

**Comment by aristidesfl** [comment]
@divmain any progress on this?

**Comment by asfaltboy** [comment]
@aristidesfl have you tried [last documentation solution][1] ?

It was concieved by @rpbaptist in #36 and seems to work well on a variety of platforms (at least those that can run [git-gui][2]).

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/commit.md#signing-your-commits-with-gpg
[2]: https://github.com/spearce/git-gui

**Comment by aristidesfl** [comment]
@asfaltboy `git config --global core.askpass git-gui--askpass` has no effect.
Maybe because gpg-agent is already configured, or maybe because git has nothing to due with this password?

**Comment by asfaltboy** [comment]
@aristidesfl oops, I just noticed I only repeated what was already mentioned above :( of course no-tty is still the solution for running git -> gpg from Sublime. Not aware of any way to force `"no-tty"` argument. Nor would we would actually want to do that for users.

I think we can simply update docs with a reccomendation to run `echo "no-tty" >> ~/.gnupg/gpg.conf`?

**Comment by aristidesfl** [comment]
@asfaltboy setting up no-tty only in GitSavvy is the way to go, since it is the only program which doesn't provide a tty. Either that or providing a valid tty. Setting no-tty globally doesn't seem like a good recommendation since eventually gpg will fail silently, even when evoked from the terminal.

**Comment by asfaltboy** [comment]
Since git remains a command line tool, we depend on the arguments it supports, and I don't believe it's core gpg implementation supports specifying parameters to the gpg command.

I wouldn't say it's the only program to require `no-tty`, any GUI git tool that wraps around command-line git app, will have the same issue. For example see isaacs/github#675, [sourcetree][1] or [Tower][2].

Interesting... Looking at [sourcetree solution][3], they pass a "custom" `gpg.program` configuration for the commit command, to a script that wraps around gpg:

<img width="644" alt="screen shot 2017-04-13 at 08 53 28" src="https://cloud.githubusercontent.com/assets/321520/24993462/ad2bd8ce-2026-11e7-8bae-9e67a850e283.png">

This is a pretty awesome workaround, at least for systems that have bash, and one that we can surely implement. For windows, the current solution should already work, since windows requires an installed GnuPG client which does not default to run in terminals (no-tty not required).
(NOTE:  Windows needs confirmation).

[1]: https://confluence.atlassian.com/sourcetreekb/sourcetree-commits-fail-when-using-git-signed-commits-794199810.html
[2]: https://aaronparecki.com/2016/07/29/10/git-tower
[3]: https://confluence.atlassian.com/sourcetreekb/setup-gpg-to-sign-commits-within-sourcetree-765397791.html

**Comment by stoivo** [comment]
@asfaltboy, can you make a patch for this?

**Comment by BoGnY** [comment]
[This is my gist](https://gist.github.com/BoGnY/f9b1be6393234537c3e247f33e74094a) that explain how to enable auto-signing of Git commits for **EVERY** programs that don't support it natively..
It's specifically for Windows systems!!

**Comment by asfaltboy** [comment]
I completely forgot about this issue, very sorry. Had a bit of time today to hack up a WIP solution in #1018 , with a few points remaining to be resolved.

I was able to sign the commit by just using the provided script and settings - maybe it's enough 🤔, please chime in and leave your comments there.

**Comment by kaste** [comment]
Closing bc an PR addressing or referencing this issue has been merged.
