### ISSUE TITLE
git:fetch - don't ask for remote when there's only one

### ISSUE THREAD

**Issue by tailsu** [timbrel/GitSavvy#601]
git:push doesn't ask for a remote when there's only one anyway. git:fetch shouldn't either.

**Comment by divmain** [comment]
Thanks for opening the issue!  So, for me, using the palette commands has been ingrained into my muscle memory.  Since the default selections work so well, I am very used to pressing enter twice, for example, since I know the right thing will already be selected.  If this change were to be made, I'm concerned that the differences in keystrokes between "one remote" and "many remotes" will interfere with my workflow.

I'm going to leave this issue open for a bit, and see what opinions others might have.

**Comment by asfaltboy** [comment]
My experience in re-training key strokes is that it may take anywhere between 3-10 repetitions of the new shortcut, to not make a mistake, depending on how frequent the action is. In my opinion it's a small price to pay for 1 less keystroke overall.

**Comment by stoivo** [comment]
Either way, we should make it consistent.

**Comment by randy3k** [comment]
Actually, `git: push` does show the list of remotes (if there is no remote tracking branch and `prompt_for_tracking_branch` is false. There is no inconsistency in this regards.

**Comment by kaste** [comment]
This has been implemented in #791 and released with v2.16.5 in 2017 actually.
