### ISSUE TITLE
Edit Project Settings is 'hostile'

### ISSUE THREAD

**Issue by kaste** [timbrel/GitSavvy#954]
In the new GsEditProjectSettingsCommand you persist the project data like so

https://github.com/divmain/GitSavvy/blob/9ec1cc44455a11e1dfef89629fc7c4e8c01f6a57/common/global_events.py#L88

This is 'hostile' bc e.g. it removes all the comments from that file. (Essentially it rewrites/formats the file.) In my opinion, setting files in Sublime are not data files, but user documents, so you really shouldn't do that.

(Since I'm coming from SublimeLinter land: I noticed that you expect a top-level key 'GitSavvy' here. SublimeLinter will move away from that, and will instead expect flat key-value pairs like so 

```
settings:
	SublimeLinter.linters.flake8.disable: true
```  

We do this essentially in a #usetheplatform spirit. I _really_ would like a move in the Sublime community here, and would appreciate if GitSavvy would do the same. E.g. `GitSavvy.name_of_the_setting`. The namespacing here is important for automatic setting documentation and discovery.)

**Comment by stoivo** [comment]
The Default settings, should those be prefixed with `GitSavvt` too?

It makes sense. We just recently introduce Project settings.

**Comment by kaste** [comment]
Consider this

```
sublime.load_settings('GitSavvy.sublime-settings').get('git_path')
                       ^^^^^^^^ namespace
                                                        ^^^^^^^^ key

view.settings().get('GitSavvy.git_path')
                     ^^^^^^^^ namespace
                              ^^^^^^^^ key
```

For the first case, you're always namespaced bc Sublime merges all the settings from files with the same name. 

But, if you access the settings through a context object (the view), you're in the global namespace bc Sublime starts here with the generic 'Preferences' file. Since we now are in a public, shared key space, we must namespace our keys.

**Comment by randy3k** [comment]
@kaste The usage of the `top` level key is actually inspired by `SublimeLinter`. I am happy to hear that `SublimeLinter` is moving to flat key-value pairs. However, for `GitSavvy`, I do prefer something like

```
	"settings":
	{
		"GitSavvy": {
                           # blablabla
                }
	}
```

It is because we essentially support every setting which could be specified in the `GitSavvy.sublime-settings`. It would be much easier for users to copy the keys from that file to their project file.

Regarding `set_project_data`, there are several command actually would change `sublime-project` files, e.g., the `Remove folder from project` and `Project: Add Folder` . I don't think it is a good hobby for any users to put comments into them.

**Comment by kaste** [comment]
1. 

I think a deep object is a bad decision when using the standard settings bc you loose the merging/chaining Sublime does here for us. Basically, with a deep object, you cannot set single settings in `Preferences`, per view, per project, or per syntax. You always have to provide a full object. Following how Sublime is designed AKA #usetheplatform basically requires to use flat key-value pairs for settings. 

2. 

Putting comments in json files is pretty much encouraged by Sublime's UX. It would of course be preferable if the toggle comments command would e.g. rename the keys from `"foo"` -> `"//foo"` etc. t.i. not produce invalid json all the time.

But of course, it depends on the command a user invokes of how surprising something is. Here the command is 'EditProjectSettings' and that doesn't indicate at all a destructive action. It's also a cheap UX. If you imo really want to focus on end-user ergonomics, you open the settings, then change it, mark the change and e.g. explain via a tooltip what you did, and where the user can go from there. You would also warn if such a file has comments in it. 

Of course, I understand, nobody wants to program such a UX because it is actually an effort. As it stands, I think this is pretending a better UX.

**Comment by randy3k** [comment]
1. While your concern about deep object maybe valid for other packages, it does not applied to our case, because we only read settings from `GitSavvy.sublime-settings` and the project settings. It does not make much sense to have per view/ syntax configuration in our case. We also do not need to read the settings dynamically. A deep object imo is more natural (in our case). I could see the advantages of flat keys in SublimeLinter.

2. It is not sure it is enougaged to put comments in Preferences.sublime-settings. Even changing font size would result in losing them. I guess we may just add a warning to remaind users for the possibility of losing comments.

**Comment by asfaltboy** [comment]
Excuse my ignorance @kaste , but could you point me to reference/documentation/post where I would be able to learn more about merging/chaining that "sublime does for us when we use flat keys"; and same about the _#usetheplatform_ movement (I can only barely find some slim mentions on the web). 

I have to agree about `set_project_data` ... when Sublime doesn't retain user comments on edit, it's a bug in Sublime and we aught to file a report a ticket with [SublimeTextIssues/Core][1]. Luckily, in GitSavvy there is only one remaining place where we still use `set_project_data`:

https://github.com/divmain/GitSavvy/blob/3c2e06468c8a64c024760ee0c22ba261c08731df/core/commands/init.py#L131

Luckily, this is done in a new window which shouldn't have any settings yet if I understand the code correctly. So I'm going to close this issue for now, please re-open if there are any other points to be discussed or issues to resolve.

[1]: https://github.com/SublimeTextIssues/Core/issues

**Comment by braver** [comment]
@asfaltboy cc @kaste 
I just stumbled into this issue and would like to add some notes here.

> but could you point me to reference/documentation/post where I would be able to learn more about merging/chaining that "sublime does for us when we use flat keys";

As you probably know, Sublime reads through a stack of [settings files](https://www.sublimetext.com/docs/3/settings.html) to determine the settings that apply to any given view. A package can benefit from this behavior by accessing the end result. A lot of packages, like SublimeLinter before v4, instead opt to recreate this behavior by reading the settings files directly and then perhaps merge one or two. In most cases, package developers then forget about project settings, or OS specific settings etc. 
There is no need to write your own code to read and merge the settings files, Sublime can do it for you (which is what we mean with `#usetheplatform`). With the caveat that settings should be key-value-pairs, Sublime can't merge objects for you. If you tell your users to write their project settings like `GitSavvy.name_of_the_setting `, or deeper objects like `SublimeLinter.linters.flake8.disable`, you get project level settings for free as well. This is undocumented behavior, but I also don't think there are more that 5 packages out there that need this level of detail in their settings, so that's probably why it's not documented.

(@kaste correct me if I'm wrong)

**Comment by kaste** [comment]
@braver ✋ 

A useful example. `sublack`, the black formatter for Sublime, luckily uses `sublack.format_on_save` as a setting (instead of `sublack: {'format_on_save': true}`). I used this for an addon for SublimeLinter. I can for any given view just read `view.settings().get('sublack.format_on_save')` to determine if this view will get automatically formatted on save and then turn off all annoying linter errors this will fix for you. T.i. I *don't* have to read in project files, the view settings, and the sublack global settings.

A user can set this setting globally in `Preferences`, per project (in the project settings), or per individual view (via context menu the plugin provides), and still *I* only have to read `view.settings()...`.

**Comment by asfaltboy** [comment]
Thanks for the link and detailed explanation guys. In this case I'm all for it, since most of our settings are `prefix.settings` IIRC. What say you @randy3k @stoivo , shall we work on replacing object settings?

**Comment by randy3k** [comment]
I am open to it. But it will be painfully a lot of work.

**Comment by stoivo** [comment]
¯\_(ツ)_/¯ both are fine

**Comment by kaste** [comment]
Closing as the original issue has been resolved.
